name: Coding Standards

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: cs2pr
          php-version: 8.3

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Coding standards
        run: ./vendor/bin/phpcs -q --no-colors --report=checkstyle | cs2pr
